[package]
name = "cryptopals"
version = "0.0.0"
edition = "2021"
authors = ["mbp@sourcefrog.net"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1.0"
